# Site settings
title: Tri Nguyen
email: ductricse@gmail.com
description: "4-th year Ph.D. student"
logo_location: "https://ductri.github.io/assets/images/naruto.jpg"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ductri.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
